### ISSUE TITLE
sqlwhat-ext readthedocs build failing

### ISSUE THREAD

**Issue by rv2e** [datacamp/sqlwhat-ext#4] opened 2018-02-28 14:33 UTC
@machow commented on [Thu Dec 28 2017](https://github.com/datacamp/learn-bugs/issues/133)

http://sqlwhat-ext.readthedocs.io/en/latest/#

**Comment by rv2e** [comment] 2018-02-28 14:34
It seems to be up again

**Comment by machow** [comment] 2018-03-01 01:02
It produced an empty page with no documentation

![image](https://user-images.githubusercontent.com/2574498/36821706-55e1b248-1cc2-11e8-985c-d720feed8b9b.png)

**Comment by filipsch** [comment] 2018-04-16 15:09
Duplicate of #3

**Comment by filipsch** [comment] 2018-04-17 09:18
Fixed in https://github.com/datacamp/sqlwhat-ext/commit/60cfb72cbd9ee8e42c6cdfd71aff246c99a8357a

See http://sqlwhat-ext.readthedocs.io/en/latest/

**Closed as completed by filipsch** 2018-04-17 09:18 UTC
Labels: bug
